---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
{{- if .Values.externalDns.enabled }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.externalDns.hostname }}"
{{- end }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  ports:
    - name: http
      port: 80
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
    - name: vpn
      port: 1194
      protocol: TCP
